CC = i586-mingw32msvc-gcc

SometimesRedSomtimesBlue.exe: SometimesRedSomtimesBlue.c
	$(CC) -mwindows SometimesRedSomtimesBlue.c -o SometimesRedSomtimesBlue.exe

.PHONY : clean
clean:
	rm -f SometimesRedSomtimesBlue.exe
