[package]
name = "sometimes-red-sometimes-blue-rust-glutin"
version = "0.1.0"
authors = ["Phil <PhilboBaggins@users.noreply.github.com>"]

[dependencies]
gl = "0.14.0"
glutin = "0.30.8"
rand = "0.8.5"
